//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMwithoutAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRecord
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TaskDescription { get; set; }
        public string TaskType { get; set; }
        public string ProjectName { get; set; }
        public string Customer { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskType TaskType1 { get; set; }
    }
}
